<a href="https://colab.research.google.com/github/senaldm/machine-Learning/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import time

In [ ]:
a=torch.ones(10,5)
print(a)
b=torch.tensor([1,2,3,4,5])
print(b)
c=torch.zeros_like(a)
print(c)


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([1, 2, 3, 4, 5])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [ ]:
print(c.device)
c=c.cuda(0)
print(c.device)

cuda:0
cuda:0


In [ ]:
print(a.evice)

cpu


In [ ]:
d=5000
#CPU
start_time=time.time()
A=np.random.rand(d,d).astype(np.float32)
B=np.random.rand(d,d).astype(np.float32)
C=A.dot(B)
print("----%s seconds-----"% (time.time() - start_time))

----4.264317512512207 seconds-----


In [ ]:
#GPU
start_time=time.time()
A=torch.rand((d,d)).cuda()
B=torch.rand((d,d)).cuda()
C=torch.mm(A,B)
print("----%s seconds-----"% (time.time() - start_time))

----0.6626157760620117 seconds-----


In [ ]:
N,D=5,3

A=torch.rand((N,D),requires_grad=True)
B=torch.rand((N,D),requires_grad=True)
C=torch.rand((N,D),requires_grad=True)

#forward pass to calculate the output
tmp=A*B+C
tmp=tmp.sum()

#backward pass to calculate the gradients
tmp.backward()

print(A.data)
print(A.grad)

print(C.data)
print(C.grad)

tensor([[0.4081, 0.9269, 0.7637],
        [0.2433, 0.4676, 0.4195],
        [0.3847, 0.4066, 0.5000],
        [0.8061, 0.5599, 0.8944],
        [0.9548, 0.3664, 0.6748]])
tensor([[0.0931, 0.8211, 0.8691],
        [0.2261, 0.5035, 0.1659],
        [0.4441, 0.7093, 0.9278],
        [0.1603, 0.3577, 0.9379],
        [0.9269, 0.1502, 0.7796]])
tensor([[0.9641, 0.4747, 0.6108],
        [0.4602, 0.1201, 0.5809],
        [0.3806, 0.1455, 0.0118],
        [0.3631, 0.0069, 0.7115],
        [0.6514, 0.3522, 0.0801]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
x=torch.tensor(1.,requires_grad=True)
w=torch.tensor(2.,requires_grad=True)
b=torch.tensor(3.,requires_grad=True)

# forword pass to calculate the output
y=w*x+b

# backward pass to calculate the gradients
y.backward(retain_graph=True)
print(w.grad,b.grad)

tensor(1.) tensor(1.)


In [ ]:
y.backward(retain_graph=True)
print(w.grad,b.grad)

tensor(2.) tensor(2.)


In [40]:
N=4
d=3

X=torch.rand((N,d),requires_grad=False)
w=torch.rand((d,1),requires_grad=True)
t=torch.rand((N,1),requires_grad=False)


X=torch.cat((X,torch.ones(N,1)),dim=1)
w=torch.rand((d+1,1),requires_grad=True)
#forward propagation: calculate the predition
lr=0.01

for epoch in range(10):
  y=torch.matmul(X,w)

  #calculate the error # MSE
  L=torch.pow(y-t,2).mean()

  #backward prob: calculate the derivatives
  L.backward()

  w.data=w.data-lr*w.grad
  print(L.data)


tensor(0.6320)
tensor(0.5915)
tensor(0.5185)
tensor(0.4276)
tensor(0.3369)
tensor(0.2643)
tensor(0.2240)
tensor(0.2238)
tensor(0.2630)
tensor(0.3330)
